FROM tomcat:8.0.20-jre8

COPY camel-example-servlet-tomcat-2.14.0.war /usr/local/tomcat/webapps/
COPY groovy-2.3.8.jar /usr/local/tomcat/lib
COPY commons-collections-3.2.1.jar /usr/local/tomcat/lib
COPY serialization-1.0.jar /usr/local/tomcat/lib
